/* =====================================================================
   EDIT HERE: contact details
   whatsapp: full number with country code, digits only (e.g. 573001234567)
   Leave any field as "" to hide that button.
   ===================================================================== */
const CONFIG = {
  whatsapp: "",
  email: "info@rugerarts.com",
  instagram: "ruge_arts",
  copFallbackRate: 3400   // used only if the live exchange rate can't load
};

/* =====================================================================
   EDIT HERE: the works
   status: "available" | "sold" | "reserved" | "notforsale"
   priceUSD: number (e.g. 850) or null for "price on request"
   cm: [height, width] in centimetres, e.g. cm:[70,50]  |  year: "2025" or "2025-03" (year-month)
   cats: any of "sacred", "expressionist", "aboriginal", "equestrian", "animals", "realist"
   shows: ids from SHOWS below, for works that were exhibited
   hero:true shows that work in the hero (and leaves it out of the gallery)
   Gallery order: available first, then sold, then not for sale; within each, the order below.
   ===================================================================== */
const WORKS = [
  { id:"estocada", title:"Estocada", year:"2024-07", medium:"acrylic", size:"", cm:[120,80], priceUSD:3000, status:"available", w:1444, h:1800, hero:true,
    cats:["expressionist"], shows:["fragmentos", "penultima"],
    desc:{ en:"A self-portrait in a beret, with an ironic look that nods to French existentialism. One hand holds up the face, carrying the weight of thought. The other grips a sword seen head-on, so the point aims straight at whoever is looking. Thinking too much is a burden, and that same clarity is also a weapon.",
           es:"Un autorretrato con boina y mirada irónica, en referencia al existencialismo francés. Una mano sostiene el propio rostro, cargando el peso de lo que piensa. La otra empuña una espada vista de frente, de modo que la punta apunta directo al espectador. Pensar demasiado es una carga, y esa misma lucidez es también un arma." } },
  { id:"hands-to-my-head", title:"Hands to My Head", year:"2023-05", medium:"acrylic", size:"", cm:[40,30], priceUSD:null, status:"notforsale", w:1450, h:1800,
    cats:["expressionist"], shows:[],
    desc:{ en:"A face broken into planes of colour, with hands closing in around the head. Several eyes look out from different angles, as if the thought had split the face apart.",
           es:"Un rostro fragmentado en planos de color, con unas manos que se cierran alrededor de la cabeza. Varios ojos miran desde ángulos distintos, como si el pensamiento hubiera partido la cara." } },
  { id:"hodegetria", title:"Hodegetria", year:"2021", medium:"acrylic", size:"", cm:[29,21], priceUSD:null, status:"notforsale", w:1150, h:1600,
    cats:["sacred"], shows:["tiemposacro"],
    desc:{ en:"A Virgin in the Byzantine Hodegetria tradition, “she who shows the way”, with a gold halo over a red ground. It keeps the stillness of the icon while letting the brushwork stay loose.",
           es:"Una Virgen en la tradición bizantina de la Hodegetria, «la que muestra el camino», con aureola dorada sobre fondo rojo. Conserva la quietud del ícono y deja la pincelada suelta." } },
  { id:"lion", title:"Lion", year:"2023-01", medium:"acrylic", size:"", cm:[40,40], priceUSD:500, status:"sold", w:1800, h:1774,
    cats:["animals", "expressionist"], shows:[],
    desc:{ en:"A lion's head built from dragged and dripping paint. The mane breaks apart into orange and rust while the eyes stay sharp and still.",
           es:"La cabeza de un león hecha con pintura arrastrada y chorreada. La melena se deshace en naranjas y óxidos mientras los ojos se mantienen precisos y quietos." } },
  { id:"enough", title:"Enough", year:"2024-04", medium:"acrylic", size:"", cm:[90,70], priceUSD:3000, status:"available", w:1443, h:1800,
    cats:["expressionist"], shows:["fragmentos"],
    desc:{ en:"A frontal face covered in patterns and hard black outlines, in saturated colour close to stained glass. Every eye in it looks somewhere different.",
           es:"Un rostro frontal cubierto de patrones y contornos negros, en colores saturados cercanos al vitral. Cada uno de sus ojos mira hacia un lugar distinto." } },
  { id:"san-juanero", title:"San Juanero", year:"2025-01", medium:"acrylic", size:"", cm:[80,100], priceUSD:1000, status:"sold", w:1800, h:1477,
    cats:["realist"], shows:[],
    desc:{ en:"A couple dancing the sanjuanero, the traditional dance of Colombia's Huila region, against dry mountains. He kneels with his hat on the ground while her skirt opens in full colour.",
           es:"Una pareja bailando sanjuanero, el baile tradicional del Huila, frente a montañas secas. Él se arrodilla con el sombrero en el suelo mientras la falda de ella se abre llena de color." } },
  { id:"cotopaxi", title:"Cotopaxi", year:"2026-08", medium:"acrylic", size:"", cm:[29,21], priceUSD:300, status:"sold", w:1200, h:1496,
    cats:["realist"], shows:[],
    desc:{ en:"A figure in a wool poncho seen from behind, facing the snow-capped Cotopaxi volcano in the Ecuadorian Andes.",
           es:"Una figura con ruana vista de espaldas, frente al volcán nevado Cotopaxi en los Andes ecuatorianos." } },
  { id:"fire", title:"Fire", year:"2023-01", medium:"acrylic", size:"", cm:[120,90], priceUSD:1500, status:"sold", w:1137, h:1600,
    cats:["expressionist"], shows:[],
    desc:{ en:"Vertical strokes of black, blue and orange around a column of light, reflected below as if on water. Somewhere between a burning forest and a city at night.",
           es:"Pinceladas verticales de negro, azul y naranja alrededor de una columna de luz que se refleja abajo como sobre el agua. Algo entre un bosque en llamas y una ciudad de noche." } },
  { id:"hope", title:"Hope", year:"2024-10", medium:"acrylic", size:"", cm:[61,45.5], priceUSD:null, status:"notforsale", w:1357, h:1800,
    cats:["expressionist"], shows:[],
    desc:{ en:"A child on a red bicycle riding into an explosion of warm colour. The strokes radiate out from the small figure like light.",
           es:"Un niño en una bicicleta roja que avanza hacia una explosión de color cálido. Las pinceladas salen de la pequeña figura como si fueran luz." } },
  { id:"juan-azul", title:"Juan Azul", year:"2023-07", medium:"acrylic", size:"", cm:[70,50], priceUSD:2000, status:"sold", w:1259, h:1800,
    cats:["expressionist"], shows:[],
    desc:{ en:"A figure in blues broken into cubist planes, where other faces and forms appear between the shapes.",
           es:"Una figura en azules partida en planos cubistas, donde otros rostros y formas aparecen entre las figuras geométricas." } },
  { id:"danza", title:"Danza", year:"2026-08", medium:"acrylic", size:"", cm:[50,40], priceUSD:1000, status:"sold", w:1257, h:1800,
    cats:["realist"], shows:[],
    desc:{ en:"A bullfight seen as a dance. The matador turns the red cape as the bull passes, and the crowd dissolves into the background.",
           es:"Una corrida vista como una danza. El torero gira el capote rojo mientras pasa el toro, y el público se disuelve en el fondo." } },
  { id:"cheval", title:"Cheval", year:"2025-12", medium:"acrylic", size:"", cm:[50,40], priceUSD:500, status:"sold", w:1422, h:1800,
    cats:["equestrian", "animals", "expressionist"], shows:[],
    desc:{ en:"A horse's head and neck in thick, sculpted strokes of ochre, orange and teal.",
           es:"La cabeza y el cuello de un caballo en pinceladas gruesas y esculpidas de ocre, naranja y verde azulado." } },
  { id:"equestrian-i", title:"Equilum", year:"2026-01", medium:"acrylic", size:"", cm:[61,45.5], priceUSD:1000, status:"sold", w:1436, h:1800,
    cats:["equestrian", "animals", "realist"], shows:[],
    desc:{ en:"A rider and her horse clearing a show-jumping fence, painted in a realist register. The tension is in the front legs folding over the bar.",
           es:"Una jinete y su caballo saltando un obstáculo, pintados en un registro realista. La tensión está en las patas delanteras que se doblan sobre la barra." } },
  { id:"proyeccion", title:"Proyección", year:"2024-05", medium:"acrylic", size:"", cm:[60,50], priceUSD:2000, status:"sold", w:1501, h:1800,
    cats:["expressionist"], shows:["fragmentos"],
    desc:{ en:"A face built from geometric bands of red, yellow and blue that fold into each other like a labyrinth.",
           es:"Un rostro construido con bandas geométricas de rojo, amarillo y azul que se pliegan unas sobre otras como un laberinto." } },
  { id:"pajaractilus", title:"Pajaractilus", year:"2023-02", medium:"acrylic", size:"", cm:[50,40], priceUSD:2000, status:"available", w:1191, h:1512,
    cats:["aboriginal", "animals"], shows:[],
    desc:{ en:"Half bird, half pterodactyl, as the title suggests. The body is filled with line and dot patterns against a burning orange halo.",
           es:"Mitad pájaro y mitad pterodáctilo, como sugiere el título. El cuerpo está lleno de líneas y puntos sobre un halo naranja encendido." } },
  { id:"mantilla", title:"Mantilla", year:"2024-03", medium:"acrylic", size:"", cm:[50,40], priceUSD:500, status:"available", w:1441, h:1800,
    cats:["expressionist"], shows:[],
    desc:{ en:"A tribute to the Santander painter Jorge Mantilla Caballero, after his series Cuando caen las estatuas. The seated figure, eyes closed, looks carved more than painted, a monument coming apart into blocks of colour against a dripping green ground. What was built to stand forever starts to give way.",
           es:"Un homenaje al pintor santandereano Jorge Mantilla Caballero, a partir de su serie Cuando caen las estatuas. La figura sentada, con los ojos cerrados, parece tallada más que pintada. Es un monumento que se deshace en bloques de color sobre un fondo verde chorreado, y lo que se hizo para quedarse de pie empieza a ceder." } },
  { id:"ratzinger", title:"El pensamiento de Joseph", year:"2026-09", medium:"", size:"", cm:[90,70], priceUSD:3000, status:"sold", w:1335, h:1667,
    cats:["sacred", "realist"], shows:["ratzinger2026"],
    desc:{ en:"A black-and-white portrait of Joseph Ratzinger, Pope Benedict XVI, smiling with his chin on his hand and a crucifix behind him. The title points to the theologian more than the pope, a man caught in the middle of a thought.",
           es:"Un retrato en blanco y negro de Joseph Ratzinger, el papa Benedicto XVI, sonriendo con el mentón apoyado en la mano y un crucifijo detrás. El título apunta más al teólogo que al papa, un hombre sorprendido en medio de un pensamiento." } },
  { id:"kookaburra", title:"Kookaburra", year:"2023-01", medium:"acrylic", size:"", cm:[50,40], priceUSD:1000, status:"sold", w:1299, h:1800,
    cats:["aboriginal", "animals"], shows:[],
    desc:{ en:"A kookaburra in black silhouette with fine white line work on a red ground, inspired by the painting traditions of northern Australia.",
           es:"Un kookaburra en silueta negra con finas líneas blancas sobre fondo rojo, inspirado en las tradiciones pictóricas del norte de Australia." } },
  { id:"kangaroo1", title:"Red Sand", year:"2022-12", medium:"acrylic", size:"", cm:[30,40], priceUSD:1000, status:"sold", w:1024, h:733,
    cats:["aboriginal", "animals"], shows:[],
    desc:{ en:"A kangaroo in mid-leap drawn in white lines and dot patterns over deep red, inspired by the painting traditions of northern Australia.",
           es:"Un canguro en pleno salto, dibujado con líneas blancas y puntos sobre un rojo profundo, inspirado en las tradiciones pictóricas del norte de Australia." } },
  { id:"kangaroo2-3", title:"Kangarú", year:"2023-02", medium:"acrylic", size:"", cm:[56,70], priceUSD:3000, status:"sold", w:1512, h:1200,
    cats:["aboriginal", "animals"], shows:["coniunctio","floridablanca2023"],
    desc:{ en:"A kangaroo in motion filled with dot work and patterned bands over a textured orange ground.",
           es:"Un canguro en movimiento lleno de puntillismo y bandas de patrones sobre un fondo naranja texturizado." } },
  { id:"tiger1", title:"Tiger I", year:"2023-01", medium:"acrylic", size:"", cm:[30,40], priceUSD:1000, status:"available", w:1024, h:768,
    cats:["animals", "expressionist"], shows:[],
    desc:{ en:"A big cat's head emerging from loose, dripping strokes of ochre and grey-blue.",
           es:"La cabeza de un felino que surge de pinceladas sueltas y chorreadas en ocre y gris azulado." } },
  { id:"tiger2", title:"Tiger II", year:"2023-03", medium:"acrylic", size:"", cm:[65,95], priceUSD:2000, status:"available", w:979, h:648,
    cats:["aboriginal","animals"], shows:[],
    desc:{ en:"A big cat outlined in yellow, its body filled with patterns drawn from Aboriginal painting, against a dotted blue ground.",
           es:"Un felino delineado en amarillo, con el cuerpo lleno de patrones tomados de la pintura aborigen, sobre un fondo azul punteado." } },
  { id:"still", title:"Still", year:"2026-09", medium:"acrylic", size:"", cm:[30,23], priceUSD:500, status:"available", w:1408, h:1800,
    cats:["animals"], shows:[],
    desc:{ en:"A tiger half submerged in still water among lily pads, with reeds and orange flowers behind it. Only the head breaks the surface, calm and watchful.",
           es:"Un tigre medio sumergido en agua quieta entre hojas de nenúfar, con juncos y flores naranjas detrás. Solo la cabeza rompe la superficie, tranquila y atenta." } },
  { id:"toro", title:"Toro", year:"2026-08", medium:"acrylic", size:"", cm:[18,13], priceUSD:300, status:"available", w:1129, h:1600,
    cats:["animals","expressionist"], shows:[],
    desc:{ en:"A bull charging across the ring, built from thick strokes of ochre and rust against bands of red and deep blue.",
           es:"Un toro que embiste a través del ruedo, construido con pinceladas gruesas de ocre y óxido sobre franjas de rojo y azul profundo." } },
  { id:"phanteon", title:"Phanteon", year:"2023-03", medium:"acrylic", size:"", cm:[45.5,61], priceUSD:1000, status:"sold", w:608, h:445,
    cats:["expressionist"], shows:[],
    desc:{ en:"An armoured figure crossing a turbulent landscape of blues and golds, somewhere between myth and science fiction.",
           es:"Una figura con armadura que atraviesa un paisaje turbulento de azules y dorados, entre el mito y la ciencia ficción." } },
  { id:"horse-i", title:"Horse I", year:"2026-02", medium:"acrylic", size:"", cm:[50,40], priceUSD:500, status:"available", w:1447, h:1800,
    cats:["equestrian", "animals"], shows:[],
    desc:{ en:"A white horse standing in a green field, painted in light, broken strokes over a dark background.",
           es:"Un caballo blanco de pie en un potrero verde, pintado con pinceladas claras y quebradas sobre un fondo oscuro." } },
  { id:"horse-ii", title:"Horse II", year:"2026-02", medium:"acrylic", size:"", cm:[50,40], priceUSD:500, status:"available", w:1417, h:1800,
    cats:["equestrian", "animals"], shows:[],
    desc:{ en:"A brown horse with a white blaze looking straight at the viewer, framed by trees and a warm sky.",
           es:"Un caballo castaño con lucero blanco que mira de frente al espectador, rodeado de árboles y un cielo cálido." } }
];

/* Short text shown in the hero next to the logo (one paragraph) */
const EXPLORE = {
  en: ["“Explorations” brings together my first years as a painter since I began in 2021, through Australian fauna in an Aboriginal key, cubism and the expressionist figure, to the figurative and equestrian work of recent years. It bears this name because it gathers that journey without hiding its changes of direction. It is a search for a language of my own, recognisable for now in a loaded, visible brushstroke, and a way of exploring what happens inside the human being."],
  es: ["“Exploraciones” reúne mis primeros años como pintor desde que empecé en 2021, pasando por la fauna australiana en clave aborigen, el cubismo y la figura expresionista, hasta lo figurativo y lo ecuestre de los últimos años. Lleva este nombre porque recoge ese recorrido sin esconder sus cambios de rumbo. Es la búsqueda de un lenguaje propio, que por ahora se reconoce en la pincelada cargada y visible, y una forma de explorar lo que pasa por dentro del ser humano."]
};

/* Full text of "My Path" on the About page (one string per paragraph) */
const JOURNEY = {
  en: ["I have loved drawing since I was a child, but I didn't try painting until I was well into university. I started painting on my own, without formal training, trying my hand at Sacred Art at a time when I was exploring the ultimate questions that philosophy led me to. The only work I still keep from that period is Hodegetria, from 2021. Each stage since then has been a different path. After living with Aboriginal communities in northern Australia, I painted the country's characteristic fauna with their patterns of lines and dots. In 2023 I went through cubism, until the geometry started to feel rigid and I realised that what I wanted to paint were inner states, not shapes. That is how I arrived, in 2024, at the expressionist figure that “Enough”, Proyección, “Hope” and Estocada come from.", "In the last two years I have returned to figurative painting and begun to explore the equestrian world, partly through commissions and partly to test myself against anatomy and observation. I called this collection “Explorations” because it gathers that whole journey without hiding its changes of direction. It is a search for a language of my own, recognisable for now in a loaded, visible brushstroke, and also a way of exploring what happens inside. I don't want to pin myself down yet, so I see it as a beginning."],
  es: ["Desde niño me ha gustado dibujar, pero no me probé en la pintura hasta ya estar inmerso en la universidad. Empecé a pintar solo, sin escuela, probándome en el Arte Sacro en una época en la que estaba explorando las razones últimas a las que llevaba la filosofía. La única obra que conservo de esa época es Hodegetria, de 2021. Desde ahí cada etapa fue probar un camino distinto. Después de vivir con comunidades aborígenes del norte de Australia, pinté la fauna característica del país con sus patrones de líneas y puntos. En 2023 pasé por el cubismo, hasta que la geometría se me quedó rígida y me di cuenta de que lo que quería pintar eran estados interiores, no formas. Así llegué en 2024 a la figura expresionista, que es de donde salen “Enough”, Proyección, “Hope” y Estocada.", "En los últimos dos años volví a lo figurativo y comencé a explorar el mundo ecuestre, en parte por encargos y en parte para medirme con la anatomía y la observación. Le puse “Exploraciones” a esta colección porque reúne todo ese recorrido sin esconder sus cambios de rumbo. Es la búsqueda de un lenguaje propio, que por ahora se reconoce en la pincelada cargada y visible, y también una forma de explorar lo que pasa por dentro. No quiero encasillarme todavía, así que la entiendo como un comienzo."]
};

/* Exhibitions, newest first */
const SHOWS = [
  { id:"coniunctio", year:2026, title:"Coniunctio", place:{en:"Dirección Cultural UIS exhibition halls, Bucaramanga. Group show of 37 artists from 8 institutions, curated by Marcell Bohórquez Gualdrón.", es:"Salas de exposición de la Dirección Cultural UIS, Bucaramanga. Colectiva de 37 artistas de 8 instituciones, con curaduría de Marcell Bohórquez Gualdrón."} },
  { id:"ratzinger2026", year:2026, title:"Congreso Centenario Ratzinger", place:{en:"Universidad de La Sabana, Chía, 24 to 26 September. Solo display of El pensamiento de Joseph during the three days of the congress.", es:"Universidad de La Sabana, Chía, del 24 al 26 de septiembre. Exhibición individual de El pensamiento de Joseph durante los tres días del congreso."} },
  { id:"penultima", year:2026, title:"La Penúltima Cena II", place:{en:"Universidad Industrial de Santander. Group show curated by Marcell Bohórquez Gualdrón.", es:"Universidad Industrial de Santander. Colectiva con curaduría de Marcell Bohórquez Gualdrón."} },
  { id:"fragmentos", year:2026, title:"Fragmentos del Inconsciente II", place:{en:"Museo de Bellas Artes de Bucaramanga. Group show curated by Marcell Bohórquez Gualdrón.", es:"Museo de Bellas Artes de Bucaramanga. Colectiva con curaduría de Marcell Bohórquez Gualdrón."} },
  { id:"tiemposacro", year:2024, title:"Tiempo Sacro", place:{en:"Galería Cónclave, Bucaramanga. Group show of sacred art.", es:"Galería Cónclave, Bucaramanga. Muestra colectiva de arte sacro."} },
  { id:"sabana2024", year:2024, title:{en:"Solo exhibition", es:"Exposición individual"}, place:{en:"Universidad de La Sabana, Chía.", es:"Universidad de La Sabana, Chía."} },
  { id:"floridablanca2023", year:2023, title:{en:"Institutional exhibition", es:"Exhibición institucional"}, place:{en:"Floridablanca Police headquarters, Santander. Kangarú was shown during the second half of the year, as part of an alliance with local artists.", es:"Sede de la Policía de Floridablanca, Santander. Kangarú se exhibió durante el segundo semestre, en una alianza con artistas locales."} }
];

/* ===================================================================== */
const T = {
  en:{
    "nav.works":"Works","nav.about":"About","nav.contact":"Contact",
    "hero.lede":"Juan Felipe Ruge Rodríguez, Visual Artist.",
    "header.role":"Visual Artist",
    "hero.invite":"Come in and enjoy “Explorations”, my first collection.",
    "hero.cta":"See the Works",
    "works.title":"Works","works.legend":"Red dot means sold",
    "filter.all":"All","filter.available":"Available","filter.sold":"Sold",
    "works.empty":"No works match these filters.",
    "cat.all":"All Themes","cat.sacred":"Sacred Art","cat.expressionist":"Cubist & Expressionist","cat.aboriginal":"Aboriginal-Inspired","cat.equestrian":"Equestrian","cat.animals":"Animals","cat.realist":"Realist Figure",
    "sort.label":"Sort","sort.default":"Featured","sort.asc":"Price: Low to High","sort.desc":"Price: High to Low","sort.old":"Oldest First","sort.new":"Newest First",
    "exhibited":"Exhibited",
    "explore.title":"“Explorations”","featured.title":"Featured Work","featured.more":"View Details",
    "medium.acrylic":"Acrylic on Canvas",
    "status.available":"Available","status.sold":"Sold","status.reserved":"Reserved","status.notforsale":"Not for Sale",
    "price.request":"Price on Request",
    "price.cop":"≈ {cop} COP at today's rate",
    "ask.whatsapp":"Ask on WhatsApp","ask.email":"Ask by Email",
    "ask.msg":"Hi! I'm interested in the painting \"{t}\" that I saw on RugeR Arts.",
    "ask.soldmsg":"Hi! I saw \"{t}\" on RugeR Arts. I know it's not available, but I'd like to know about similar work or a commission.",
    "ask.similar":"Ask About Similar Work",
    "about.title":"About",
    "about.caption":"Juan Felipe Ruge in front of one of his works.",
    "about.bio":"Juan Felipe Ruge Rodríguez (Bogotá, 2001) is an artist from Bucaramanga whose work moves between gestural expressionism and a close look at the human condition. He is currently studying Industrial Engineering at Universidad de La Sabana. Trained in Philosophy in Australia (UNDA), where he lived alongside Aboriginal communities in the north of the country, he makes painting a dialogue between cultures.",
    "about.s0":"“I like painting semi-figurative scenes because I feel an exaggerated body gives away better what's going on in the head.",
    "about.s1":"I focus mainly on the expression of hands and eyes. In most of my paintings I care less about anatomical accuracy than about that physical evidence of an inner state, and this carries over even into my paintings of animals: kangaroos, big cats, birds.",
    "about.s2":"I work in acrylic on canvas and I like the brushstrokes to show. I don't try to hide the process. I'd rather you see the corrections, the layers left underneath and the places where the paint went on too thick. A finished painting that doesn't show how it was made feels less alive to me.",
    "about.s3":"My training comes from two sides that don't always talk to each other. Engineering gave me a relationship with structure and with problems framed well enough to be solved. Philosophy left me the questions I keep painting: what consciousness does with itself, why we think, and why perhaps we shouldn't do it so much. A good part of my work comes from there.",
    "about.s4":"What I look for in a painting of mine is that it gives something back to whoever looks at it, a presence that unsettles a little and makes you stay a while longer than planned. When someone stops in front of one of my figures and feels the figure is looking back, the painting is working the way I want it to.”",
    "about.cite":"Interview for the Museo de Bellas Artes de Bucaramanga",
    "about.shows":"Exhibitions",
    "studio.ratzinger":"At the Congreso Centenario Ratzinger.","studio.process":"Creative process.","studio.gabo":"With the artist Gabo Sierra.",
    
    "contact.title":"Get in Touch",
    "contact.text":"To buy a painting or commission a work, write to me directly. I usually reply within a day or two.",
    "contact.commissions":"I also paint on commission. Rates vary with size, technique, complexity and the creative work behind the composition.",
    "journey.title":"My Journey","nav.home":"Home","explore.more":"About Me","others.title":"Studio Paintings","studio.photo":"Photographing Equilum.","studio.enough":"Beside “Enough”.","studio.journey":"Walking through the Palacio del Arte y la Moda, Medellín.",
    "contact.whatsapp":"WhatsApp","contact.email":"Email","contact.instagram":"Instagram",
    "contact.msg":"Hi Felipe! I found your work on RugeR Arts.",
    "footer.rights":"All images are of original works. Reproduction without written permission is prohibited.","footer.privacy":"Privacy Policy","footer.terms":"Terms of Sale",
    "viewer.prev":"Previous Work","viewer.next":"Next Work","viewer.close":"Close",
    "open":"View {t}"
  },
  es:{
    "nav.works":"Obras","nav.about":"Sobre Mí","nav.contact":"Contacto",
    "hero.lede":"Juan Felipe Ruge Rodríguez, Artista Plástico.",
    "header.role":"Artista Plástico",
    "hero.invite":"Te invito a recorrer y disfrutar “Exploraciones”, mi primera colección.",
    "hero.cta":"Ver las Obras",
    "works.title":"Obras","works.legend":"Punto rojo significa vendida",
    "filter.all":"Todas","filter.available":"Disponibles","filter.sold":"Vendidas",
    "works.empty":"Ninguna obra coincide con estos filtros.",
    "cat.all":"Todos los Temas","cat.sacred":"Arte Sacro","cat.expressionist":"Cubista y Expresionista","cat.aboriginal":"Inspiración Aborigen","cat.equestrian":"Ecuestre","cat.animals":"Animales","cat.realist":"Figura Realista",
    "sort.label":"Ordenar","sort.default":"Destacadas","sort.asc":"Precio: Menor a Mayor","sort.desc":"Precio: Mayor a Menor","sort.old":"Más Antiguas Primero","sort.new":"Más Recientes Primero",
    "exhibited":"Exhibida en",
    "explore.title":"“Exploraciones”","featured.title":"Obra Destacada","featured.more":"Ver Detalles",
    "medium.acrylic":"Acrílico sobre Lienzo",
    "status.available":"Disponible","status.sold":"Vendida","status.reserved":"Reservada","status.notforsale":"No Está a la Venta",
    "price.request":"Precio a Consultar",
    "price.cop":"≈ {cop} COP a la tasa de hoy",
    "ask.whatsapp":"Preguntar por WhatsApp","ask.email":"Preguntar por Correo",
    "ask.msg":"¡Hola! Me interesa la obra \"{t}\" que vi en RugeR Arts.",
    "ask.soldmsg":"¡Hola! Vi \"{t}\" en RugeR Arts. Sé que no está disponible, pero me gustaría saber de obras similares o un encargo.",
    "ask.similar":"Preguntar por Obras Similares",
    "about.title":"Sobre Mí",
    "about.caption":"Juan Felipe Ruge junto a una de sus obras.",
    "about.bio":"Juan Felipe Ruge Rodríguez (Bogotá, 2001) es un artista bumangués cuya obra transita entre el expresionismo gestual y una mirada profunda hacia la condición humana. Actualmente es estudiante de Ingeniería Industrial en la Universidad de La Sabana. Formado en Filosofía en Australia (UNDA) y habiendo vivido con comunidades aborígenes del norte del país, su pintura se convierte en un diálogo de distintas culturas.",
    "about.s0":"“Me gusta pintar escenas semi-figurativas porque siento que un cuerpo exagerado delata mejor lo que hay en la cabeza.",
    "about.s1":"Me enfoco principalmente en la expresión de las manos y los ojos. En la mayoría de mis cuadros, me interesa menos lo anatómicamente correcto que esa evidencia física de un estado interior; esto se refleja incluso en mis pinturas de animales (canguros, felinos, aves).",
    "about.s2":"Trabajo en acrílico sobre lienzo y me gusta que las pinceladas sean visibles. No busco esconder el proceso. Prefiero que se vean las correcciones, las capas que quedaron debajo y los sitios donde el color se cargó de más. Un cuadro terminado que no muestra cómo se hizo me resulta menos vivo.",
    "about.s3":"Mi formación viene de dos lados que no siempre conversan. La ingeniería me dio una relación con la estructura y con los problemas bien planteados para poderse resolver. La filosofía me dejó las preguntas que sigo pintando: qué hace la conciencia consigo misma, para qué pensamos y por qué quizá no deberíamos hacerlo tanto. Buena parte de mi obra sale de ahí.",
    "about.s4":"Lo que busco en un cuadro mío es que devuelva algo al que lo mira, una presencia que incomode un poco y que obligue a quedarse un rato más de lo previsto. Cuando alguien se detiene frente a una de mis figuras y siente que la figura también lo mira, el cuadro está funcionando como me interesa.”",
    "about.cite":"Entrevista para el Museo de Bellas Artes de Bucaramanga",
    "about.shows":"Exposiciones",
    "studio.ratzinger":"En el Congreso Centenario Ratzinger.","studio.process":"Proceso creativo.","studio.gabo":"Con el artista Gabo Sierra.",
    
    "contact.title":"Contacto",
    "contact.text":"Para comprar una obra o hacer un encargo, escríbeme directamente. Suelo responder en uno o dos días.",
    "contact.commissions":"También pinto por encargo. Las tarifas varían según el tamaño, la técnica, la complejidad y el trabajo creativo de la composición.",
    "journey.title":"Mi Recorrido","nav.home":"Inicio","explore.more":"Sobre Mí","others.title":"Estudios de Taller","studio.photo":"Fotografiando Equilum.","studio.enough":"Junto a “Enough”.","studio.journey":"Recorriendo el Palacio del Arte y la Moda, Medellín.",
    "contact.whatsapp":"WhatsApp","contact.email":"Correo","contact.instagram":"Instagram",
    "contact.msg":"¡Hola Felipe! Encontré tu obra en RugeR Arts.",
    "footer.rights":"Todas las imágenes son de obras originales. Prohibida su reproducción sin autorización escrita.","footer.privacy":"Política de Privacidad","footer.terms":"Términos y Condiciones",
    "viewer.prev":"Obra Anterior","viewer.next":"Obra Siguiente","viewer.close":"Cerrar",
    "open":"Ver {t}"
  }
};
